# Generated by Django 3.2.23 on 2026-03-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_otxalienvaultapikey_leakcheckapikey'),
        ('threatIntel', '0002_manualindicator_threatintelreportsetting_leakcheckdata_checked_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatintelreportsetting',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
