# Generated by Django 3.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPScanAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
