# Generated by Django 3.2.23 on 2026-03-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_otxalienvaultapikey_leakcheckapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSignatory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='report_signatures/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='dashboard.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
