# Generated by Django 3.2.23 on 2026-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_report_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsignatory',
            name='role',
            field=models.CharField(choices=[('prepared', 'Disusun Oleh / Prepared By'), ('reviewed', 'Diketahui Oleh / Reviewed By'), ('approved', 'Disahkan Oleh / Approved By')], default='prepared', max_length=20),
        ),
    ]
