# Generated by Django 3.2.23 on 2026-02-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_vulnerabilityreportsetting_executive_summary_description_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='google_chat_hook_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_google_chat',
            field=models.BooleanField(default=False),
        ),
    ]
