# Generated by Django 3.2.23 on 2026-03-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_otxalienvaultapikey_leakcheckapikey'),
        ('scanEngine', '0006_add_google_chat_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityreportsetting',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
